### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Togetogean** [SieR-VR/usc-app#12]
As title said i just installed the app click start then this happen.

My phone is POCO M4 Pro
![Screenshot_2022-09-05-22-32-45-912_com example unnamed_sdvx_clone](https://user-images.githubusercontent.com/37516051/188482882-d5a96dd7-2141-4318-9b04-213174e5952c.jpg)

**Comment by sblzdddd** [comment]
I have the same problems too. I uses 2 devices but remains same error. The only solution now is to change the skin. I uses Nightfall which doesn't pop any errors

**Comment by anonymoususer0001** [comment]
This is a late response but I had the same issue and figured out how to solve it
Go to ~/Android/data/com.example.unnamed_sdvx_clone/files/skins/Default/scripts/songselect and open up songwheel.lua
Edit the following lines:
game.LoadSkinSample("menu_click")
game.LoadSkinSample("click-02")
game.LoadSkinSample("woosh")
So that it becomes:
game.LoadSkinSample("menu_click.wav")
game.LoadSkinSample("click-02.wav")
game.LoadSkinSample("woosh.wav")
Hope this helps

**Comment by SieR-VR** [comment]
Sorry for late, 

> This is a late response but I had the same issue and figured out how to solve it Go to ~/Android/data/com.example.unnamed_sdvx_clone/files/skins/Default/scripts/songselect and open up songwheel.lua Edit the following lines: game.LoadSkinSample("menu_click") game.LoadSkinSample("click-02") game.LoadSkinSample("woosh") So that it becomes: game.LoadSkinSample("menu_click.wav") game.LoadSkinSample("click-02.wav") game.LoadSkinSample("woosh.wav") Hope this helps

This will works fine. I committed those codes at usc-default-android repository, so you can use it.
